name: GitHub Actions Demo
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
    build:
        ## ...
        runs-on: ubuntu-latest
        steps:

         - name: Check out the repo
           uses: actions/checkout@v3

         - name: Build the Docker image
           run: docker build . --file ./Dockerfile --tag inline_scanner_test:v1.0

         - name: lw-scanner
           run: | 
            curl -L https://github.com/lacework/lacework-vulnerability-scanner/releases/latest/download/lw-scanner-linux-amd64 -o lw-scanner
            chmod +x lw-scanner
            result=`./lw-scanner image evaluate inline_scanner_test v1.0`
            echo $result
            curl \
            -X POST \
            $URL \
            -H "Content-Type: application/json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            --data '{ "body": $result }'
           env:
             URL: ${{ github.event.pull_request.comments_url }}
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
             LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }}
             LW_ACCESS_TOKEN: ${{ secrets.LW_ACCESS_TOKEN }}
